



CREATE TABLE http_request (

id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
ip VARCHAR(500) NOT NULL,
request VARCHAR(100) NOT NULL,
status VARCHAR(30) NOT NULL,
user_agent VARCHAR(500) NOT NULL,
req_date TIMESTAMP NOT NULL

);